### ISSUE TITLE
Note functionality

### ISSUE THREAD

**Issue by criteriamor** [francepack/trapper-keeper-ui#4]
- The user can add a title to the note.
- The user can dynamically add an indefinite number of list items for that note.
- The user can dynamically remove any or all of those list items (one at a time).
- The user can delete the note (similar to the archiving in the gif below), and when they delete the note, they should be returned back to the home page.
- The user can mark list items as completed. When they do so, the completed list item should move to the bottom of the form.

**Comment by taylorsperry** [comment]
Creating new issue for the last bullet point.
